#############################################################################
# Makefile for building: release/Bezier
# Generated by qmake (2.01a) (Qt 4.8.2) on: seg out 13 17:18:06 2014
# Project:  Bezier.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Bezier.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/Modelo/curva.cpp \
		src/Modelo/ponto.cpp \
		src/Controle/xmlparser.cpp \
		src/Vista/janelaprincipal.cpp \
		src/Controle/limite.cpp \
		src/Vista/janelaopcoes.cpp \
		src/Modelo/definicoes.cpp \
		src/Main.cpp moc_janelaprincipal.cpp
OBJECTS       = curva.o \
		ponto.o \
		xmlparser.o \
		janelaprincipal.o \
		limite.o \
		janelaopcoes.o \
		definicoes.o \
		Main.o \
		moc_janelaprincipal.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Bezier.pro
QMAKE_TARGET  = Bezier
DESTDIR       = release/
TARGET        = release/Bezier

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) release/ || $(MKDIR) release/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Bezier.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Bezier.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Bezier.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Bezier1.0.0 || $(MKDIR) .tmp/Bezier1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Bezier1.0.0/ && $(COPY_FILE) --parents src/Modelo/curva.h src/Modelo/ponto.h src/Controle/xmlparser.h src/Vista/janelaprincipal.h src/comum.h src/Controle/limite.h src/Vista/janelaopcoes.h src/Modelo/definicoes.h .tmp/Bezier1.0.0/ && $(COPY_FILE) --parents src/Modelo/curva.cpp src/Modelo/ponto.cpp src/Controle/xmlparser.cpp src/Vista/janelaprincipal.cpp src/Controle/limite.cpp src/Vista/janelaopcoes.cpp src/Modelo/definicoes.cpp src/Main.cpp .tmp/Bezier1.0.0/ && (cd `dirname .tmp/Bezier1.0.0` && $(TAR) Bezier1.0.0.tar Bezier1.0.0 && $(COMPRESS) Bezier1.0.0.tar) && $(MOVE) `dirname .tmp/Bezier1.0.0`/Bezier1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Bezier1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_janelaprincipal.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_janelaprincipal.cpp
moc_janelaprincipal.cpp: src/Vista/janelaopcoes.h \
		src/Vista/janelaprincipal.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/Vista/janelaprincipal.h -o moc_janelaprincipal.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

curva.o: src/Modelo/curva.cpp src/Modelo/curva.h \
		src/Modelo/ponto.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o curva.o src/Modelo/curva.cpp

ponto.o: src/Modelo/ponto.cpp src/Modelo/ponto.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ponto.o src/Modelo/ponto.cpp

xmlparser.o: src/Controle/xmlparser.cpp src/Controle/xmlparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmlparser.o src/Controle/xmlparser.cpp

janelaprincipal.o: src/Vista/janelaprincipal.cpp src/Vista/janelaprincipal.h \
		src/Vista/janelaopcoes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o janelaprincipal.o src/Vista/janelaprincipal.cpp

limite.o: src/Controle/limite.cpp src/Controle/limite.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o limite.o src/Controle/limite.cpp

janelaopcoes.o: src/Vista/janelaopcoes.cpp src/Vista/janelaopcoes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o janelaopcoes.o src/Vista/janelaopcoes.cpp

definicoes.o: src/Modelo/definicoes.cpp src/Modelo/definicoes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o definicoes.o src/Modelo/definicoes.cpp

Main.o: src/Main.cpp src/Vista/janelaprincipal.h \
		src/Vista/janelaopcoes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o src/Main.cpp

moc_janelaprincipal.o: moc_janelaprincipal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_janelaprincipal.o moc_janelaprincipal.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

